### PR TITLE
updated queue dependency to v2.2.0

### PR DESCRIPTION
**Pull request by christian-bromann**
- fixed library since Queue v2.0.0 breaks API
- added some comments to describe implementation
- exposed `start` and `stop` function

### CODE REVIEW

**Comment by vvo** [comment]
Can you add tests around start and stop? Fi you need start and stop for webdriverjs?

Thank you.

**Comment by christian-bromann** [comment]
Hi @vvo 

I added a test for starting and stopping a queue in `chainit`. Right, I need it for all the upcoming features regarding multi-browser tests. I will probably add another `skip` function.

But first I have to figure out why the tests are failing.

**Comment by christian-bromann** [comment]
Well of course I haven't any secure keys deposited in the `.travis.yml`.
So you have to trust me here ;-)

**Comment by vvo** [comment]
This looks good, thank you.

**Pull request merged**
